apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bpdmstransactionerrormanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bpdmstransactionerrormanager
    spec:
      containers:
        - name: bpdmstransactionerrormanager
          image: cstarregistry.azurecr.io/bpdmstransactionerrormanager
          ports:
          - containerPort: 8080