apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtdmstransactionerrormanager
spec:
  replicas: 10
  selector:
    matchLabels:
      app: rtdmstransactionerrormanager
  template:
    metadata:
      labels:
        app: rtdmstransactionerrormanager
    spec:
      containers:
        - name: rtdmstransactionerrormanager
          image: cstaruatregistry.azurecr.io/rtdmstransactionerrormanager
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: rtdmstransactionerrormanager
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: eventhub-common
            - configMapRef:
                name: rtdmstransactionerrormanager
            - configMapRef:
                name: jvm
      hostAliases:
        - hostnames:
            - bpd-event-uat.servicebus.windows.net
          ip: 10.70.67.5
