apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmstransactionerrormanager
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: bpdmstransactionerrormanager
  template:
    metadata:
      labels:
        app: bpdmstransactionerrormanager
    spec:
      containers:
        - name: bpdmstransactionerrormanager
          image: cstarpacr.azurecr.io/bpdmstransactionerrormanager
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: application-insights
            - secretRef:
                name: bpdmstransactionerrormanager
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: eventhub-common
            - configMapRef:
                name: bpdmstransactionerrormanager
            - configMapRef:
                name: jvm
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 600Mi
